# -*- coding: utf-8 -*-
"""All_Imports.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfn3iEg0GwN8Ow6IQ2de4vcX2XAlDTo_
"""

import numpy as np
import matplotlib.pyplot as plt
import time
import tensorflow as tf
from tensorflow import keras
#from tensorflow.keras import layers
from tensorflow.keras.layers import GaussianNoise, BatchNormalization, Input, Multiply, Lambda, Dropout, Conv2D, Flatten, Dense, Reshape, Conv2DTranspose, Concatenate, Embedding, ReLU
from tensorflow.python.keras.layers.advanced_activations import LeakyReLU
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.initializers import TruncatedNormal, Orthogonal, RandomNormal
from tensorflow.keras.constraints import Constraint
import Ising_Functions as is_fun
from datetime import datetime
import keras.backend as K
from keras.models import load_model 
from keras.layers.merge import _Merge
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split